config/routes.rb
Rails.application.routes.draw do
  root to: "lists#index"
  resources :lists 
  resources :bookmarks, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates_uniqueness_of :movie_id, :scope => [:list_id]
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_one_attached :photo
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  before_action :set_bookmark, only: [:show, :destroy]

  def index
    @bookmarks = Bookmark.all
  end

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    if @bookmark.save
      redirect_to @bookmark.list, notice: "New Record Saved"
    else
      render :new
    end
  end

  def destroy
    @bookmark.destroy
    redirect_to bookmarks_url, notice: 'Bookmark was successfully destroyed.'
  end


  private

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :destroy]

  def index
    @lists = List.all
  end

  def show
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to @list, notice: "New Record Saved"
    else
      render :new
    end
  end

  def destroy
    @list.destroy
    redirect_to lists_url, notice: 'List was successfully destroyed.'
  end


  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :photo)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<div class="container mt-3" style="padding: 90px">

  <h1>New Bookmark</h1>

  <%= simple_form_for @bookmark do |f| %>
  <%= f.association :movie %>
  <%= f.association :list %>
  <%= f.input :comment %>
  <%= f.button :submit %>
  <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top">
      <a class="logo">
        <%= image_tag "logo-small.jpg", alt: "Ticket" %>
      </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to 'My Lists', lists_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'New List', new_list_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <img class="avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://kitt.lewagon.com/placeholder/users/MarcWeitzmann" />
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
            </div>
          </li>
        </ul>
      </div>

    </div>

    <%= yield %>

  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for(@list) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :photo, as: :file %>
  </div>

  <div class="form-actions btn btn-primary">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/lists/index.html.erb
<div class="container mt-3" style="padding: 90px">
  
  <div class="banner">
    <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
      <div class="carousel-inner">
        <div class="carousel-item picture-small active">

          <% if @lists.first.present? && @lists.first.photo.attached? %>
            <%= cl_image_tag @lists.first.photo.key, alt: "List Picture", class: "d-block w-100" %>
              <div class="carousel-caption d-none d-md-block">
                <h1><%= @lists.first.name %></h1>
              </div>
          <% else %>
            <%= image_tag "girl.jpg", alt: "List Picture", class: "d-block w-100" %>
            <div class="carousel-caption d-none d-md-block">
              <h1>Girl</h1>
            </div>
          <% end %>
        </div>

        <% @lists.drop(1).each do |list| %>
          <div class="carousel-item picture-small">

            <% if list.photo.attached? %>
              <div class="image-size" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path list.photo.key, height: 300, crop: :fill %>')">
              </div>
              <div class="carousel-caption d-none d-md-block">
                <h1><%= list.name %></h1>
              </div>
            <% else %>
                <div class="image-size" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= image_path "girl.jpg", height: 300, crop: :fill %>')">
                </div>
                <div class="carousel-caption d-none d-md-block">
                  <h1>Girl</h1>
                </div>
            <% end %>
          </div>
        <% end %>

      </div>

    </div>

  </div>

  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
  </a>
    
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
  </a>


  <div class="row">
    <% @lists.each do |list| %>
      <div class="col mt-3">
        <div class="card" style="width: 18rem;">

          <% if @lists.first.present? && @lists.first.photo.attached? %>
            <div class="image-size" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path list.photo.key, height: 300, crop: :fill %>')">
            </div>
          <% else %>
            <div class="image-size" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= image_path "girl.jpg", height: 300, crop: :fill %>')">
            </div>
          <% end %>

            <div class="card-body">
              <h5 class="card-title"><%= list.name %></h5>
              <p class="card-text">No. of movies: <%= list.movies.count %></p> 
              <%= link_to 'Show Movies', list, class: "btn btn-primary" %>
              <%= link_to 'Delete List', list, method: :delete, data: { confirm: 'Are you sure?' } %>
            </div>
        </div>
      </div>    
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<div class="container mt-3" style="padding: 90px">

  <h1>New List</h1>

  <%= render 'form', list: @list %>

</div>

app/views/lists/show.html.erb
<div class="container mt-3" style="padding: 90px">

  <h1> <%= @list.name %> Movies </h1>

    <div class="container">
      <%= cl_image_tag @list.photo.key, width: 960, height: 200, crop: :fill  %>
    </div>

  <% @list.movies.each do |movie| %>

    <div class="card" style="width: 24rem;">
      <img src="<%= movie.poster_url %>" class="card-img-top" style="height: 160px" alt="...">
      <div class="card-body">
        <h5 class="card-title"><%= movie.title %></h5>
        <p class="card-text"><%= movie.overview %></p>
        
        <% @list.bookmarks.each do |bookmark| %>
          <p><%= bookmark.comment %></p>
          <hr>
        <% end %>

        <a href="#" class="btn btn-primary">Delete Bookmark</a>
      </div>
    </div>
  <% end %>

<div class="btn btn-primary">
  <%= link_to  "Create a Bookmark", new_bookmark_path, class: "btn btm-primary" %>
</div>


</div>